[[main]]
  identifier = "eucf/_index"
  name = "EUCF"
  pageRef = "/eucf/"
  weight = 2

[[main]]
  identifier = "news/_index"
  name = "Novinky"
  pageRef = "/news/"
  weight = 3

[[main]]
  identifier = "about/_index"
  name = "O nás"
  pageRef = "/about/"
  weight = 4

[[main]]
  identifier = "team/_index"
  name = "Tým"
  pageRef = "/team"
  weight = 5

[[main]]
  identifier = "contact/_index"
  name = "Kontakt"
  pageRef = "/contact"
  weight = 6